apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.network/elastic: "true"
    io.kompose.service: webapi
  name: webapi
spec:
  containers:
  - image: webapi
    name: webapi
    ports:
    - containerPort: 80
    resources: {}
  restartPolicy: OnFailure
status: {}
